import java.awt.Color;
import java.awt.event.ActionEvent;

import javax.swing.JFrame;

/**
 *
 * @author DELL
 */
public class ProfileFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProfileFrame
     */
    public ProfileFrame() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        changeUserNameButton = new javax.swing.JButton();
        ChangePasswordButton = new javax.swing.JButton();
        addBankCardButton = new javax.swing.JButton();
        removeCardButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        deactivateAccountButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        SettingsButton = new javax.swing.JButton();
        addPicture = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\melis\\Downloads\\anime\\WhatsApp Image 2022-05-06 at 22.21.05.jpeg")); // NOI18N

        changeUserNameButton.setBackground(new java.awt.Color(220, 250, 100));
        changeUserNameButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        changeUserNameButton.setText("ChangeUserName");
        changeUserNameButton.setPreferredSize(new java.awt.Dimension(220, 23));
        changeUserNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserNameButtonActionPerformed(evt);
            }
        });

        ChangePasswordButton.setBackground(new java.awt.Color(220, 250, 100));
        ChangePasswordButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ChangePasswordButton.setText("ChangePassword");
        ChangePasswordButton.setPreferredSize(new java.awt.Dimension(220, 23));
        ChangePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordButtonActionPerformed(evt);
            }
        });

        addBankCardButton.setBackground(new java.awt.Color(220, 250, 100));
        addBankCardButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        addBankCardButton.setText("AddBankCard");
        addBankCardButton.setPreferredSize(new java.awt.Dimension(220, 23));
        addBankCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBankCardButtonActionPerformed(evt);
            }
        });

        removeCardButton.setBackground(new java.awt.Color(220, 250, 100));
        removeCardButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        removeCardButton.setText("RemoveBankCard");
        removeCardButton.setPreferredSize(new java.awt.Dimension(220, 23));
        removeCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCardButtonActionPerformed(evt);
            }
        });

        logOutButton.setBackground(new java.awt.Color(220, 250, 100));
        logOutButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        logOutButton.setText("LogOut");
        logOutButton.setPreferredSize(new java.awt.Dimension(220, 23));
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        deactivateAccountButton.setBackground(new java.awt.Color(220, 250, 100));
        deactivateAccountButton.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        deactivateAccountButton.setText("DeactivateAccount");
        deactivateAccountButton.setPreferredSize(new java.awt.Dimension(220, 23));
        deactivateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateAccountButtonActionPerformed(evt);
            }
        });
       // 
        jLabel1.setIcon(new javax.swing.ImageIcon( "C:\\Users\\melis\\OneDrive\\Masaüstü\\projec\\WhatsApp Image 2022-05-12 at 03.18.17.jpeg")); // NOI18N

        SettingsButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\melis\\Downloads\\1564529_mechanism_options_settings_configuration_setting_icon.png")); // NOI18N
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });

        addPicture.setIcon(new javax.swing.ImageIcon("C:\\Users\\melis\\OneDrive\\Masaüstü\\projec\\WhatsApp Image 2022-05-12 at 03.18.24.jpeg")); // NOI18N
        addPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPictureActionPerformed(evt);
            }
        });

        homeButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\melis\\Downloads\\anime\\326656_home_icon.png")); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        profileButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\melis\\Downloads\\5402435_account_profile_user_avatar_man_icon.png")); // NOI18N
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(220, 250, 100));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton3.setText("ChangeIncome");
        jButton3.setPreferredSize(new java.awt.Dimension(220, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SettingsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileButton)
                .addGap(171, 171, 171))
            .addGroup(layout.createSequentialGroup()
                .addGap(660, 660, 660)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBankCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deactivateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(changeUserNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ChangePasswordButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 632, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(profileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(addPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addComponent(changeUserNameButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(ChangePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addBankCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removeCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(homeButton)))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deactivateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(481, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {
        settings s = new settings();
        s.setVisible(true);
        dispose();
    }

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        ProfileFrame pf = new ProfileFrame();
        pf.setVisible(true);
        dispose();
    }

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        MenuJFrame pf = new MenuJFrame();
        pf.setVisible(true);
        dispose();
    }

    private void changeUserNameButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        UserNameChangeFrame un = new UserNameChangeFrame();
        un.setVisible(true);
    }                                                    

    private void ChangePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        ChangePasswordFrame p = new ChangePasswordFrame();
        p.setVisible(true);
    }                                                    

    private void addBankCardButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        CardStatementJFrame c = new CardStatementJFrame();
        c.setVisible(true);
    }                                                 

    private void removeCardButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        RemoveBankCard r = new RemoveBankCard();
        r.setVisible(true);
    }                                                

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        userEnter u = new userEnter();
        u.setVisible(true);
        dispose();
    }                                            

    private void deactivateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        Profile.removeUser(Profile.getUser());
        userEnter u = new userEnter();
        u.setVisible(true);
        dispose();
    }                                                       

    private void addPictureActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ChangePasswordButton;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JButton addBankCardButton;
    private javax.swing.JButton addPicture;
    private javax.swing.JButton changeUserNameButton;
    private javax.swing.JButton deactivateAccountButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton removeCardButton;
    // End of variables declaration                   
}
